name: Java DevOps Secure CI Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:

  # JOB 1 - BUILD + TEST
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Project
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-build-files
          path: target/

  # JOB 2 - TRIVY SCAN
  trivy_scan:
    name: Trivy Filesystem Scan
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: table

  # JOB 3 - DOWNLOAD ARTIFACT
  download_artifact:
    name: Download Artifact
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: java-build-files
          path: downloaded-files

      - name: Verify Artifact
        run: ls -R downloaded-files

  # JOB 4 - STATUS CHECK
  pipeline_status:
    name: Final Status Check
    needs:
      - build_test
      - trivy_scan
      - download_artifact
    runs-on: ubuntu-latest
    if: success()

    steps:
      - run: echo "🎉 Java DevOps Pipeline Passed Successfully ✅"
